#!/bin/bash
read -p "Enter your AWS secret access key: " key
if [ -z "$key" ] 
then
  echo 'Inputs cannot be blank please try again'
  exit
fi
 
export AWS_ACCESS_KEY_ID=AKIAW5IWB6RRXLVDZSGR
export AWS_SECRET_ACCESS_KEY=$key

